- src/xrc/src/api.rs
This PR includes a minor improvement to the log messages when a rate fails to be extracted from an exchange.
> Update log message when an a failure to extract rate occurs

- src/xrc/src/api/test.rs
- src/xrc/src/environment.rs
- src/xrc/src/lib.rs
This PR ups the cycle cost for the `get_exchange_rate` endpoint to `10_000_000_000` cycles. `5_000_000_000` is immediately refunded.
> feat: Up the cycle cost to `10_000_000_000`

- src/xrc/src/api.rs
- src/xrc/src/lib.rs
This PR removes an unused arm from `CallExchangeError` and provides an error to read format when calling an exchange fails.
> refactor: Clean up errors from transforms

- src/xrc/src/api.rs
- src/xrc/src/environment.rs
This is a minor refactor to have `get_exchange_rate` to exit early if there are not enough cycles attach to the request.
> refactor: Check for cycles earlier in the call.

- src/xrc/src/main.rs
This PR uses `canister_inspect_message` to ensure only messages from other canisters or requests to the metrics are allowed.
> feat: Add `canister_inspect_message`

- src/xrc/src/api/test.rs
- src/xrc/src/environment.rs
- src/xrc/src/exchanges.rs
- src/xrc/src/forex.rs
This PR adds tests for requesting crypto/fiat pairs. It fixes a bug found while testing in `ForexRateStore::get`. The bug occurs when determining the `query_timestamp`. If the timestamp is zero, the forex rate store panics due to an underflow detected.
> feat(test): Adds tests for crypto/fiat pairs.

- src/xrc/src/api/test.rs
This PR adds unit tests for forex rate pairs when calling `get_exchange_rate`.
> feat: Add forex rate pair unit tests

- canister_ids.json
- src/monitor-canister/monitor-canister.did
- src/monitor-canister/src/periodic.rs
This PR updates the monitor canister with the following:
* A canister ID on mainnet.
* The anonymous principal error variant field.
* Updating the amount of cycles to send.
> feat: Add monitor canister ID to canister_ids.json, update candid, and cycles cost.

- canister_ids.json
- src/xrc/src/api.rs
- src/xrc/src/api/test.rs
- src/xrc/src/candid.rs
- src/xrc/src/lib.rs
- src/xrc/src/utils.rs
- src/xrc/xrc.did
This PR allows the NNS dapp to query rates freely from the XRC. It also adds the `Pending` error variant as the canister will likely be deployed before the `Pending Request` feature makes it in.
> feat: Allow the NNS dapp to query rates freely.

- src/xrc/src/api.rs
- src/xrc/src/inflight.rs
- src/xrc/src/lib.rs
- src/xrc/src/rate_limiting.rs
This PR adds the ability to track pending requests. A request is determined as `pending` when one of the assets is currently in process of being retrieved from the exchanges.
For example, the XRC receives a request `X` for `ICP/BTC` at timestamp `100`. While the XRC starts processing request `X`, another request (`Y`) for `BTC/USDT` at timestamp `100` is received. The XRC canister adds the following symbol-timestamp pairs to the tracking set from request `X`: 
`("ICP", 100)` and `("BTC", 100)`. 
While waiting for request `X`'s results, the XRC begins to process request `Y`. As request `Y` contains the symbol-timestamp pair `("BTC", 100)`, request `Y` is determined to be `pending` and the `Pending` error is returned to the user.
> feat: Add the ability to mark requests as pending

- src/xrc/src/utils.rs
Currently, if a request doesn't specify a timestamp, the start of the most recent minute is used as the timestamp.
Since it takes some time for exchanges to offer data for the current minute, this approach results in many failed calls.
This PR changes the behavior: The start of the current minute is only used if at least 30 seconds have passed. Otherwise, the start of the previous minute is used.
> Changing the behavior when no timestamp is provided in a request

- src/xrc/src/api/test.rs
This PR adds a unit test when a `crypto/USDT` pair is requested. The intended functionality is that the canister will only call for the `crypto/USDT` from the exchanges as `USDT` is the base unit.
> feat: Add crypto/USDT unit test

- src/xrc-tests/src/tests.rs
- src/xrc-tests/src/tests/can_successfully_retrieve_rate.rs
This PR moves the `can_successfully_retrieve_rate` test to a separate module. As we add additional `e2e` tests, the singular `tests` module will become quite cluttered. This is the first PR to address that.
> chore: Move `can_successfully_retrieve_rate` test to separate module

- src/xrc-tests/src/container.rs
- src/xrc-tests/src/container/utils.rs
This PR updates the e2e tests response builder to allow for different content types when responding to the canister HTTP outcalls. The PR was created to start adding forex sources (some sources return XML) to the e2e tests.
> refactor: Allow e2e tests to have different response bodies beyond JSON.

- src/monitor-canister/monitor-canister.did
- src/monitor-canister/src/periodic.rs
This PR adds a sampling schedule to the monitor canister. For each entry in the schedule, the monitor canister will collect `1_000` entries.
The current schedule is set as follows:
1. Every 1 minute
2. Every 3 minutes
3. Every 5 minutes
4. Every 10 minutes
> feat: Update the monitor canister to contain a sampling schedule.

- src/monitor-canister/src/periodic.rs
This PR removes a small bug in the monitor canister that was causing the canister to become stuck syncing at the last scheduled interval.
> `bugfix`: Monitor canister sync could not complete full schedule

- src/xrc/src/api.rs
This PR cleans up the following:
* Moves the `get_normalized_timestamp` call to inside each handle function.
* Moves the `match` statement to a `route_request` function for readability.
* Passes a reference of the request into each handle function instead of separate parameters.
This work is done in preparation for the new `timestamp = null` feature.
> `refactor`: Refactor handle functions to take in the entire request

- src/xrc/src/api.rs
- src/xrc/src/api/test.rs
- src/xrc/src/lib.rs
- src/xrc/src/periodic.rs
This PR implements the following:
1. If the request contains a timestamp = null, the XRC will get the current normalized timestamp. 
2. If the requested assets with the current normalized timestamp are considered to be inflight, the XRC then goes back 1 additional minute (labeled internally as a past normalized timestamp).
3. If requested assets with the past normalized timestamp *are not* in the cache, the minimum fee is charged and the caller receives a pending error.
4. If requested assets with the past normalized timestamp *are* in the cache, the base cost fee is charged and the caller receives the requested rate.
> `feature`: If timestamp = null and the request is inflight, use the previous minute in hopes to return a rate.

- src/xrc/src/api.rs
- src/xrc/src/api/test.rs
When deploying the timestamp = null feature, ForexQuoteAssetNotFound errors started to populate the logs. This lead to the discovery that the refactor missed the inversion of the base and quote assets for fiat-crypto pairs.
This PR addresses the issue by inverting the base and quote assets for a fiat-crypto pair. The inverted request is then passed in to the `handle_crypto_base_fiat_quote_pair` handle function. To ensure coverage to avoid this problem from occurring in the future, additional unit tests were added to ensure this case is covered.
> `bugfix`: fiat-crypto pairs were not handled correctly in earlier refactor

- src/xrc/src/lib.rs
- src/xrc/src/utils.rs
The new TVL canister will make use of the exchange rate canister.
Since it is another "system canister", it should be exempt from paying cycles.
This PR adds its canister ID (`ewh3f-3qaaa-aaaap-aazjq-cai`) to the list of privileged canisters.
> Adding the TVL canister to the list of privileged canisters

- src/xrc/src/api.rs
- src/xrc/src/api/test.rs
- src/xrc/src/environment.rs
- src/xrc/src/lib.rs
- src/xrc/src/utils.rs
There is a risk that an attacker might try to get an exchange rate based on the rates of a small number of exchanges into the cache by timing the request carefully.
The CMC might then be served this rate.
This PR changes adds the restriction that cached rates may only be served to all privileged canisters if they are based on a specific minimum number of collected rates.
> Require a minimum number of sources for privileged canisters when serving from the cache

- scripts/build-wasm
- scripts/e2e-tests
- src/xrc/Cargo.toml
- src/xrc/src/forex.rs
This PR adds a feature flag to disable the forex timezone offset. This causes issues in determining what values will be used when creating system tests that expect hand built responses.
> `feat`: Add `disable-forex-timezone-offset` for system testing purposes

- .github/workflows/docker-build.yml
This PR updates the wasm build to turn *on* IPv4 support.
> `chore`: Update the wasm build to enable IPv4 support

- src/xrc/src/api.rs
- src/xrc/src/lib.rs
- src/xrc/src/stablecoin.rs
- src/xrc/src/utils.rs
This PR resolves the discovered possibility of division by zero errors while inverting a rate. This is accomplished by updating the division in `utils::invert_rate` (renamed to `utils::checked_invert_rate`) to `checked_div` and returning the result.
* When used to invert a `QueriedExchangeRate`, the failed results are filtered out using `filter_map`.
* When inverting a stablecoin rate, if the rate fails to be inverted, a `CallExchangeError::NoRateFound` is returned.
> `bugfix`: Check the division when inverting the rate to avoid division by zero errors.

- src/xrc/src/api.rs
- src/xrc/src/api/test.rs
- src/xrc/src/errors.rs
- src/xrc/src/lib.rs
This PR introduces a future timestamp check for rate requests. If the timestamp is too far in the future, it is rejected and the minimum fee will be charged.
> `feat`: Requested timestamps that are too far in the future should be rejected and charged the minimum fee.

- src/xrc/src/api.rs
- src/xrc/src/exchanges.rs
This PR should resolve the issue with the Okx exchange receiving the following error: `Http body exceeds size limit of 212 bytes`.
In addition, this adds the caller to the log statements.
> `bugfix`: Raise Okx max response bytes

- src/xrc/src/periodic.rs
This PR adds a guard to the periodic task for updating the forex store. While we have been extremely careful to dealing with panics, this guard better ensures the state is set properly in case we have missed something.
> bugfix: Add a updating forex store guard for safety purposes

- README.md
- src/xrc/src/forex.rs
- src/xrc/src/lib.rs
- src/xrc/src/periodic.rs
The XRC does't get forex rates from the Bank of Israel.
This PR removes this forex source to make sure that the XRC doesn't make useless calls.
> Removing the Bank of Israel

- src/xrc/src/api.rs
- src/xrc/src/api/dashboard.rs
- src/xrc/src/forex.rs
- src/xrc/src/lib.rs
- src/xrc/src/request_log.rs
This PR adds a dashboard to the canister. This will give us a better view into how the XRC is being used.
* A metadata table to see the following:
* Decimals
* Number of exchanges available
* Number of forex sources available
* List of the privileged canister IDs
* Tables with information on the active forex collectors:
* Sources that have been collected
* Tables containing requests and responses including the timestamp and caller
> feat: Add dashboard to view most recent requests

- src/xrc/src/forex.rs
- src/xrc/src/periodic.rs
This PR fixes a bug that caused the Central Bank of Bosnia Herzegovina to be added on a Saturday. The bug came from the query timestamp (B.H. needs to use +1 day to get the rates for the prior day) being returned as the timestamp that the rates should be assigned to.
> `bugfix`: Central Bank of Bosnia Herzegovina added rates on a Saturday

- src/xrc/src/api.rs
- src/xrc/src/api/dashboard.rs
- src/xrc/src/request_log.rs
- src/xrc/src/utils.rs
This PR improves upon the `sanitize_request` function to clean up symbols with invalid characters. This is important as the dashboard could end up rendering the asset symbols as HTML.
> `bugfix`: Sanitize requests when logged to avoid possible injection attacks on the dashboard.

- src/xrc/src/forex.rs
The computation for end-of-day used `max` instead of `min` (as `get_utc_offset` returns a negative number for western sources). Fixing this raised a problem in type casting as we were casting a potentially negative value to `u64`.
> Fix EOD offset computation

- src/xrc/src/forex/georgia.rs
- src/xrc/src/forex/italy.rs
- src/xrc/src/forex/nepal.rs
- src/xrc/src/forex/switzerland.rs
This is a simple PR to increase the max response bytes to a higher limit for the most recently added forex sources. Some of the responses are much larger than expected.
> `bugfix`: Increase `max response bytes` for newly added forex sources

- src/xrc-tests/docker/base.Dockerfile
- src/xrc/src/api/test.rs
- src/xrc/src/forex.rs
- src/xrc/src/forex/italy.rs
- src/xrc/src/periodic.rs
This PR changes the going back policy when looking up forex rates to go back up to 7 days, and only to consider days where the CXDR rate has at least 4 rates reported. It also fix various tests that depend on that by adding artificial values for CXDR with enough sources.
> New going back policy for forex rate retrieval

- src/xrc/src/api/dashboard.rs
- src/xrc/src/periodic.rs
A minor cleanup for the dashboard to include the response timestamp, remove the decimals, and sort the forex sources.
> `refactor`: Cleanup dashboard

- src/xrc-tests/src/lib.rs
- src/xrc-tests/src/tests.rs
- src/xrc-tests/src/tests/caching.rs
This PR adds an e2e test for the crypto caching mechanism.
---
Setup:
* Deploy mock FOREX data providers and exchanges with a large response delay
Start replicas and deploy the XRC, configured to use the mock data sources
Runbook:
1. Request the same exchange rate many times per second for a bounded time, e.g., 1 minute
2. Assert that all requests are answered with the same rate with a small delay after the first response (due to caching in the XRC)
Success criteria:
* All queries are handled correctly
> test: Add caching `e2e` test

- src/xrc-tests/src/tests.rs
- src/xrc-tests/src/tests/determinism.rs
- src/xrc-tests/src/tests/misbehavior.rs
This PR adds the determinism e2e test.
---
Setup:
* Deploy mock FOREX data providers and exchanges, all configured to be malicious
* Start replicas and deploy the XRC, configured to use the mock data sources
Runbook:
* Request exchange rate for various cryptocurrency and fiat currency pairs
* Assert that errors are returned indicating that no rates could be determined
Success criteria:
* All queries return the expected values
> test: Add determinism e2e test

- src/xrc-tests/src/tests.rs
- src/xrc/src/forex.rs
- src/xrc/src/lib.rs
- src/xrc/src/utils.rs
This PR removes the square-root operations on floating-point numbers, which require a conversion to floating-point numbers and then back.
Instead, an integer square-root function is introduced and used. The function has the following property:
If `y = integer_sqrt(x)`, then `y*y <= x` and `(y+1) * (y+1) > x`.
It is worth noting that the square-root function over real numbers doesn't have this property, so the new function is in some sense more precise.
> Removing floating-point square-root operations

- .github/actions/build/action.yml
- .github/workflows/docker-build.yml
- .github/workflows/release.yml
This PR updates the GitHub workflows to allow to create a release via a tag.
> `chore`: Improve workflows for release

- src/xrc/src/lib.rs
The subnet `uzr34` was recently updated and now charges the [lower prices](https://internetcomputer.org/docs/current/developer-docs/gas-cost) for HTTPS outcalls.
This PR adapts the pricing of the exchange rate canister accordingly, reducing all prices by a factor of 10.
> Update cycle pricing

- src/monitor-canister/src/periodic.rs
This PR updates the monitor canister to query for the following rates:
* ICP/CXDR
* BTC/BTT
* ETH/EUR
* SHIB/BTC
It also removes the limit for sampling. The canister will now sample every 5 minutes.
> `chore`: Update monitor canister to query for additional rates to fully exercise the XRC.

- Cargo.lock
- Cargo.toml
- src/ic-xrc-types/Cargo.toml
- src/monitor-canister/Cargo.toml
- src/monitor-canister/src/api.rs
- src/monitor-canister/src/main.rs
- src/monitor-canister/src/periodic.rs
- src/monitor-canister/src/types.rs
- src/xrc-tests/Cargo.toml
- src/xrc/Cargo.toml
- src/xrc/src/environment.rs
- src/xrc/src/exchanges.rs
- src/xrc/src/forex.rs
- src/xrc/src/http.rs
- src/xrc/src/lib.rs
- src/xrc/src/main.rs
- src/xrc/src/types.rs
- src/xrc/src/utils.rs
This PR updates the XRC to use the latest `candid` (0.9.1), `ic-cdk` (0.10.0), and `serde-xml-rs` (0.6.0).
> chore: Update to latest candid, ic-cdk, and serde-xml-rs

- .github/workflows/tests.yml
- Dockerfile
- rust-toolchain.toml
Upgrading Rust to 1.71.1 due to the latest security notice found [here](https://blog.rust-lang.org/2023/08/03/cve-2023-38497.html).
> chore: Upgrade Rust version

- src/xrc/src/exchanges.rs
The exchange Mexc is failing on mainnet due to an increase in HTTP header size. To solve this, this PR bumps the default max response bytes to 3KiB. This will bump *every* exchange in order to be provide buffer for every exchange source.
> fix: Bump all exchanges to default max response bytes to 3KiB

- src/xrc/src/api/dashboard.rs
The boundary nodes were recently upgrade to prevent browsers from guessing the content type of responses from raw. While it looks like this behavior will change back to the prior behavior, fixing the problem, it is better to set the content type header anyways to prevent further issues down the line.
> fix: Set /dashboard content-type

- .github/workflows/tests.yml
- Cargo.lock
- Cargo.toml
- dfx.json
This PR updates the exchange rate canister's dependencies.
dfx: 0.16.0
candid: 0.10.2
ic-cdk: 0.12.1
ic-cdk-macros: 0.8.4
> chore: Upgrade exchange rate canister dependencies (dfx, candid, ic-cdk)

- src/xrc/src/api.rs
- src/xrc/src/lib.rs
If no rates are retained while instantiating a `QueriedExchangeRate`, the inner `rates` field can become empty. This causes a panic when inverting and dividing rates. This PR patches this behavior to allow the logic to reach the inevitable `validate` calls the occur in each `handle_*_pair` function in `api.rs`.
This is not a major bug as we have implemented `Drop` for our various guards, but it is still a good idea to remove panics.
> fix: Remove access by index when inverting and dividing rates

- canister_ids.json
- dfx.json
- scripts/build-wasm
- src/monitor-canister/src/periodic.rs
- src/xrc/src/exchanges.rs
- src/xrc/src/forex.rs
This PR does the following:
1. Raises the required number of cycles needed to submit HTTPS requests on a 13-node subnet.
2. Lowers the minimum number of forexes required to return a forex rate if IPv4 is not available.
3. Fixes a bug in the build-wasm script if no features are enabled then we should just compile the wasm.
> fix: Enable beta release by upping the required cycles and lowering the minimum forexes if IPv4 support is not available.

- src/xrc/src/api.rs
- src/xrc/src/api/test.rs
- src/xrc/src/exchanges.rs
- Adds a filter to remove failed exchanges in subsequent out calls within the same `get_exchange_rate` call
- Update testing
> fix: Prevent repeated calls to failed exchanges

- Cargo.lock
- Cargo.toml
- Dockerfile
- scripts/build-mock-wasm
- src/xrc_mock/Cargo.toml
- src/xrc_mock/src/lib.rs
- src/xrc_mock/src/main.rs
- src/xrc_mock/xrc.did
It can be useful to have an exchange rate canister available in a test environment without it making API calls to exchanges.
Instead of everybody implementing their own mock, we should provide one in this repo so it's easy to find and share.
In plan to use this in the snsdemo repo which creates the test environment used by nns-dapp.
1. Copied https://github.com/dfinity/ic/tree/master/rs/rosetta-api/tvl/xrc_mock to `src/xrc_mock`
2. Slightly changed the [Cargo.toml](https://github.com/dfinity/ic/blob/3dfaa18aa073deb23899ffe0601eff78697804da/rs/rosetta-api/tvl/xrc_mock/Cargo.toml) to work in the current repo.
3. Removed [BUILD.bazel](https://github.com/dfinity/ic/blob/master/rs/rosetta-api/tvl/xrc_mock/BUILD.bazel) as this repo doesn't use `bazel`.
4. Added a build script.
5. Fix the docker …
> feat: Copy xrc_mock from tvl in ic repo

- .github/workflows/release.yml
- Dockerfile
- dfx.json
To make it easy for scripts setting up test environments to download a WASM for the XRC mock to install.
1. Included a section for `xrc_mock` in `dfx.json` so the wasm can be built using `dfx build` to include canister metadata.
2. Update `Dockerfile` to include building `xrc_mock`.
3. Update `.github/workflows/release.yml` to include the mock wasm in the assets.
This [draft release](https://github.com/dfinity/exchange-rate-canister/releases/tag/untagged-c19a212e13b8615dd065) was created with the workflow.
> build: Include xrc_mock in the release

- .github/workflows/tests.yml
Since MacOS 12 is deprecated, the version needs to be bumped to 13 to fix CI.
> fix: Bumping the MacOS version from 12 to 13

- INTERFACE_SPECIFICATION.md
- README.md
- src/xrc/xrc.did
In an effort to have clear and consistent documentation of the API of system canisters, this PR adds a dedicated `INTERFACE_SPECIFICATION.md` file.
> chore: Adding the interface specification

- .github/workflows/docker-build.yml
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Dockerfile
Ubuntu 20.04 is near end-of-life. GitHub will stop support in April. This PR addresses that by bumping everything to 22.04.
> chore: Update workflows to ubuntu-22.04
